### ISSUE TITLE
Who We Are page not working

### ISSUE THREAD

**Issue by christinehobson** [gerbilsinspace/gateway#25]
I wanted to create links from the elders' names on the Who We Are page to their individual profiles in the People section. However, as soon as I created a link to Caleb's profile, the whole Who We Are page stopped working. I've removed the link, but the Who We Are page still doesn't seem to be working and I'm not sure what I can do to fix it. Are you able to try and sort the page issue? Is it possible for me to add links from people's names to their profiles in the People section?

**Comment by gerbilsinspace** [comment]
Hi Christine, thanks for the bug report.

I've just pushed a fix to make the page work again, but it might not fix the linking issue you saw. Would you be able to add the link again, and see if it still causes a problem?

**Comment by gerbilsinspace** [comment]
looks like I've just had some trouble pushing this fix live, hang on a second...

**Comment by gerbilsinspace** [comment]
The fix is there now. can you make your change again and see if it blows up

**Comment by christinehobson** [comment]
Yes, it's working now, thanks, that's good. Just added the link for Caleb and will try some others. No urgency at all on this - but the purple text for the links isn't aesthetically great. Is underlining the text for links perhaps an option?

**Comment by gerbilsinspace** [comment]
I'm going to open up a new ticket about the link styling, and close this one. :)

**Comment by gerbilsinspace** [comment]
Bug for the link styling is here. https://github.com/gerbilsinspace/gateway/issues/26 - closing this ticket.
