### ISSUE TITLE
Search option not working

### ISSUE THREAD

**Issue by christinehobson** [gerbilsinspace/gateway#28]
I've been doing some updates and creating links today, and the search option is going to error after inputting 3 or 4 letters.

**Comment by gerbilsinspace** [comment]
This usually means we have a file the search is relying on that is missing or is broken in some way. Thanks for letting me know, I'll investigate as soon as I can.

**Comment by gerbilsinspace** [comment]
Looks like it is working now, closing

**Comment by christinehobson** [comment]
Hi Joe, Thanks so much for all your work on the various issues today! It looks like all of them are fine apart from this one. It's odd - if I search for Caleb, typing either Cal or Ell, it works fine. But if I search for most other people, on the 3rd letter, it goes to error. This has happened today with hob, adi, nea. With tu, it crashes on the 2nd letter. So seems there's still an issue with this if you have a chance to take a look at it again.

**Comment by gerbilsinspace** [comment]
Wow, thanks! of course I tested with Caleb. I'll look at this again shortly.

**Comment by gerbilsinspace** [comment]
Fixed using your search results. I'll close this, reopen if you find any more.
