### ISSUE TITLE
Open in new tabs

### ISSUE THREAD

**Issue by christinehobson** [gerbilsinspace/gateway#30]
On most website I think if you hold down Ctrl and click on a link, it appears in a new tab. Is it possible to do that on this site?

**Comment by gerbilsinspace** [comment]
This might be a bit too in depth as a response, so strap in.

Gateway isn't a traditional website, like most websites. It is actually one large web page pretending to be multiple pages. This lets us host the website for free, amongst other reasons.

Unfortunately, it means that I am not using traditional links, like most sites. I'm relying on https://nextjs.org/ to give us that functionality. I think we would have to wait until Next provides ctrl-click new tab functionality with their Link component. I'll see if they have a ticket and see if they are working on it.

**Comment by gerbilsinspace** [comment]
I have asked the Next team to take a look at this here. https://github.com/zeit/next.js/issues/7218

I'll let you know when / if I hear a follow up.

**Comment by gerbilsinspace** [comment]
So they've taken a look at what I've done with the code, it looks like it is a bug on our side after all. I'll reclassify this as a bug, and take a look at it soon.

**Comment by gerbilsinspace** [comment]
This should be fixed, at least for the menu

**Comment by salwa445** [comment]
[shemales]()
